// The oracle: drive real Emacs deterministically and return {text, point, mark}.
//
//   emacs -Q --batch -l <script.el>
//
// HEADLESS — no PTY. `-Q` (no init file, no site file) plus `--batch` plus a
// generated script is fully deterministic: the only state is the fixture file
// and the token list.
//
// Three experimentally verified requirements — each is silent when violated:
//
//   1. `execute-kbd-macro` runs against the SELECTED WINDOW's buffer, not the
//      current buffer. Without `(set-window-buffer (selected-window) buf)` the
//      keys execute in *scratch* and the oracle reports an empty buffer with
//      nonsense point.
//   2. `line-move-visual` must be nil, or C-n / C-p signal `end-of-buffer`
//      because visual line motion needs real window geometry.
//   3. `inhibit-message` must be t, or echo-area output pollutes stdout.
//
// A fourth, discovered here: an error inside `execute-kbd-macro` ABORTS the
// rest of the macro, whereas the real command loop just rings the bell and
// reads the next key. So the oracle runs the whole token list as ONE macro
// (preserving command-loop continuity — undo chaining, self-insert
// amalgamation, `last-command`) and, when a command signals, records the
// failure and RESTARTS the macro at the following token. A `pre-command-hook`
// counter tells us which token signalled, because one token is exactly one
// command (see keys.js).
//
// Output framing: the script writes a JSON file rather than printing
// `TEXT<<...>>` sentinels — fuzzed buffer text can contain any byte sequence,
// including the sentinel itself.

import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { tokensToEmacsKbd } from "./keys.js";
import { EMACS_SETUP } from "./parity.js";

const EMACS = process.env.EMACS_BIN || "emacs";
const TIMEOUT_MS = Number(process.env.EMACS_TIMEOUT || 15000);

// Elisp string literal. Only `\` and `"` need escaping for the ASCII payloads
// we generate; newlines are legal inside an elisp string but we escape them
// anyway so the generated script stays one form per line and stays readable.
function elisp(str) {
  return `"${String(str).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function elispList(items) {
  return `(list ${items.map(elisp).join(" ")})`;
}

function buildScript(inputPath, outPath, tokens) {
  const kbd = tokensToEmacsKbd(tokens);
  return `;; generated by emacs-oracle.js — do not edit
(require 'json)

(defvar oracle-cmd-count 0)
(defun oracle-count-command () (setq oracle-cmd-count (1+ oracle-cmd-count)))
(add-hook 'pre-command-hook #'oracle-count-command)

(let ((buf (get-buffer-create "oracle"))
      (toks ${tokens.length ? elispList(kbd) : "nil"})
      (errs '()))
  ;; GOTCHA 1: execute-kbd-macro acts on the selected window's buffer.
  (set-window-buffer (selected-window) buf)
  (with-current-buffer buf
${EMACS_SETUP.map((e) => `    ;; ${e.why}\n    ${e.form}`).join("\n")}
    (erase-buffer)
    (let ((coding-system-for-read 'utf-8-unix))
      (insert-file-contents ${elisp(inputPath)}))
    (goto-char (point-min))
    (set-mark nil)
    (deactivate-mark)
    ;; Drop the fixture insertion from the undo list so C-/ can only ever undo
    ;; the fuzzed edits. (nil re-enables recording; t would disable it.)
    (setq buffer-undo-list nil)

    (let ((n (length toks)) (idx 0) (guard 0))
      (while (and (< idx n) (< guard (+ n 5)))
        (setq guard (1+ guard))
        (setq oracle-cmd-count 0)
        (let ((rest (mapconcat 'identity (nthcdr idx toks) " ")))
          (condition-case e
              (progn (execute-kbd-macro (kbd rest)) (setq idx n))
            ;; \`quit\` (C-g) is a signal, not an error — catch both.
            ((error quit)
             (let ((failed (+ idx (max 0 (1- oracle-cmd-count)))))
               (push (list :index failed
                           :token (or (nth failed toks) "")
                           :message (error-message-string e))
                     errs)
               (setq idx (1+ failed))))))))

    (let ((coding-system-for-write 'utf-8-unix))
      (write-region
       (json-encode
        (list :text (buffer-string)
              :point (point)
              :point_max (point-max)
              :mark (or (mark t) json-null)
              :region_active (if (and transient-mark-mode mark-active) t :json-false)
              :errors (vconcat (nreverse errs))))
       nil ${elisp(outPath)} nil 'silent))))
`;
}

/**
 * Run `tokens` against `inputText` in real Emacs.
 *
 * @param {string} inputText  starting buffer contents. MUST NOT end in "\n" —
 *   ttt's loader drops a final newline (parity.js pins showTrailingNewline off),
 *   so a fixture with one would put the two buffer models one line apart.
 * @param {string[]} tokens   token stream (see keys.js).
 * @returns {{text: string, point: number, mark: number|null, regionActive: boolean,
 *            errors: {index: number, token: string, message: string}[]}}
 *   `point` and `mark` are 1-based Emacs buffer positions; `mark` is null when
 *   the mark has never been set. `errors` lists the tokens whose command
 *   signalled — a distinct outcome, not a crash: execution continued past them,
 *   exactly as the interactive command loop would.
 */
export function runEmacs(inputText, tokens) {
  if (inputText.endsWith("\n")) {
    throw new Error("emacs-oracle: fixture must not end with a newline (see parity.js)");
  }
  const dir = mkdtempSync(join(tmpdir(), "fuzz-emacs-"));
  try {
    const input = join(dir, "buffer.txt");
    const script = join(dir, "oracle.el");
    const out = join(dir, "out.json");
    writeFileSync(input, inputText, "utf8");
    writeFileSync(script, buildScript(input, out, tokens), "utf8");

    let stderr = "";
    try {
      execFileSync(EMACS, ["-Q", "--batch", "-l", script], {
        stdio: "pipe",
        timeout: TIMEOUT_MS,
        encoding: "utf8",
      });
    } catch (e) {
      stderr = (e.stderr || "") + (e.stdout || "");
      // The script itself swallows command errors; anything reaching here is a
      // harness failure (bad key description, timeout, missing emacs).
      throw new Error(`emacs-oracle: emacs failed: ${e.message}\n${stderr}`);
    }

    const raw = readFileSync(out, "utf8");
    const j = JSON.parse(raw);
    return {
      text: j.text,
      point: j.point,
      mark: j.mark === null ? null : j.mark,
      regionActive: j.region_active === true,
      errors: (j.errors || []).map((e) => ({
        index: e.index,
        token: e.token,
        message: e.message,
      })),
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}
